default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/movies.db

test:
  <<: *default
  database: db/movies.db

production:
  <<: *default
  database: db/movies_db
