default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/ratings_development.sqlite3

test:
  <<: *default
  database: db/ratings_test.sqlite3

production:
  <<: *default
  database: db/ratings_production.sqlite3
